### ISSUE TITLE
Race Condition

### ISSUE THREAD

**Issue by seankovacs** [hajipy/embedded-queue#31]
First, you made an excellent in-memory DB queue library. Good work!

There is a race condition which allows multiple workers to work the same job. There needs to be a lock system in-place surrounding the **findInactiveJobByType** method to prevent these rare race conditions. I created sample code to reproduce the problem.

```
const EmbeddedQueue = require("embedded-queue");

(async () => {
  const queue = await EmbeddedQueue.Queue.createQueue({ inMemoryOnly: true });

  queue.on(EmbeddedQueue.Event.Enqueue, (job, result) => {
    console.log(`Job Enqueue: ${job.id}`);
  });

  queue.on(EmbeddedQueue.Event.Complete, (job, result) => {
    console.log(`Job Completed: ${job.id}`);
  });

  for (var i = 0; i < 10; i++) {
    await queue.createJob({
      type: "adder",
      data: { a: 1, b: 2 },
    });
  }

  queue.process("adder", async (job) => job.data.a + job.data.b, 5);
})();
```

**Comment by hajipy** [comment]
@seankovacs 
Thank you for using it.

Bug reports are appreciated.
Please wait while I fix it.
