### ISSUE TITLE
embedded queue to run  in renderer process with sandbox db

### ISSUE THREAD

**Issue by nagappan080810** [hajipy/embedded-queue#39]
To use the embedded queue inside the renderer process as per the security guidelines, we need to enable nodeIntegration to false. When we do that nodeIntegration false, we would require an alternative for event emitter like observable or subject. Also instead of a file we need to use a sandbox database, whether there is the possibility of upgrading the embedded queue API?

**Comment by hajipy** [comment]
Embedded-queue is intended to be used in node.js or electron main process(mostly node.js).
It is unlikely that I will have time to modify it to work with renderer process.

Have you considered a way to have it used in main process and notify renderer process when an event occurs?
