### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by goldencolor** [hajipy/embedded-queue#44]
I want queues to be where I continue the logic and flow after each execution, one by one

**error:
this._currentJob is not null**

`if (updateSendResult) {
          logger.service.info(
            { updateSendResult, taskId, objId },
            '群发单个目标用户完成发送'
          );
          msgQueue.shutdown(1000, QueueEunm.SEND_MSG).then(()=>{
            setTimeout(async () => {
              // 需要延迟执行
              msgQueue.process(
                QueueEunm.SEND_MSG,
                async (job) => {
                  logger.service.info(job, QueueEunm.SEND_MSG + '队列消费中...');
                },
                1
              );
            }, _.random(1000,5000));
          });
        }`

**Comment by goldencolor** [comment]
`if (updateSendResult) {
          logger.service.info(
            { updateSendResult, taskId, objId },
            '群发单个目标用户完成发送'
          );
          msgQueue.shutdown(1000, QueueEunm.SEND_MSG).then(()=>{
            setTimeout(async () => {
              // 需要延迟执行
              msgQueue.process(
                QueueEunm.SEND_MSG,
                async (job) => {
                  logger.service.info(job, QueueEunm.SEND_MSG + '队列消费中...');
                },
                1
              );
            }, _.random(1000,5000));
          });
        }`

**Comment by hajipy** [comment]
I didn't understand what you are want to do.
But after `Queue.shutdown` was called, other method call for that queue is not assumptions.

**Comment by goldencolor** [comment]
> I didn't understand what you are want to do. But after `Queue.shutdown` was called, other method call for that queue is not assumptions.


I want to use it for user group posting, but there is an interval of 5-15 seconds between each task. I hope that after each task is executed, the task will continue to be executed after a random time through the timer.


**After each task is finished, it will continue to execute after waiting for a certain period of time. At present, once it is started, it will be executed forever. There is no process of suspending or waiting for the task.**

`
setTimeout(async() => {
          await msgQueue.shutdown(1000);
        }, 1);
        setTimeout(async () => {
          // 需要延迟执行
          msgQueue.process(
            QueueEunm.SEND_MSG,
            async (job) => {
              // logger.service.info(job, QueueEunm.SEND_MSG + '队列消费中...');
              job.data;
            },
            1
          );
        }, _.random(1000,5000));
`

**Comment by hajipy** [comment]
> There is no process of suspending or waiting for the task.

Yes. You are right, that feature is not implemented.
I'll leave issue #43 as feature request, but I don't think it can be implemented right away.

**Comment by goldencolor** [comment]
> > There is no process of suspending or waiting for the task.
> 
> Yes. You are right, that feature is not implemented. I'll leave issue #43 as feature request, but I don't think it can be implemented right away.

Do you have any suggestions? I really need him

Very anxious or where you suggest that the transformation can be achieved based on your foundation

**Comment by hajipy** [comment]
I was answered in #43 . 
Since this is a duplicate topic, I'm closing this one.
