### ISSUE TITLE
Worker/processor teardown or unregistering

### ISSUE THREAD

**Issue by emcodem** [hajipy/embedded-queue#49]
Hey hajipy, thanks for this magnificent tool.

As far as i understand (and also i clarify the terms here), you call queue.process once in order to generate a new WORKER with a specified concurrency. 
After that, you push JOB to that WORKER by calling queue.createJob where the "type" field defines the name of the previously generated queue this job shall be pushed into. 
So basically the hierarchy is like each QUEUE can have many WORKERS and each worker can have many JOBs

As far as i understand, i can do housekeeping for jobs using the job->removeJob method. 
My question is, how could i do housekeeping on the WORKERS in case i do create workers dynamically (each worker has many jobs but when the last job finished, i don't need the worker anymore)

thanks!

**Comment by hajipy** [comment]
@emcodem 
Thanks for using this library.

To answer your question, you can pass a type as the second argument to Queue.shutdown and only shutdown workers corresponding to a specific type.

Also, thank you for trying to understand the structure of this library.
As a matter of fact, a registered job is not immediately registered in a queue for a specific worker, but in a single queue. After that, the worker who is available handles the job at the head of the queue. Therefore, it is not a three-tiered hierarchy of queue, worker, and job.

**Comment by emcodem** [comment]
Wow, that was very fast, thanks a lot!
OK so if i interpret you correctly, the difference between my description and the reality is that you can have one queue with many WORKERS of the same "type" actually and a job of a given type could be picked up by the next worker (of same type) that has an available slot.

Sorry that i didnt see that the queue shutdown function is the one that actually removes workers from memory, thanks for this tipp. As far as i see, i could call the shutdown function with a timeout directly when creating the new worker type and set it to shutdown after a few hours, when it is definitely not needed anymore.

Question left is, how to do housekeeping in the database. The database only contains jobs and of course not workers (workers refer to a function in memory so they cannot really be stored). If i want to keep the database small enough, e.g. keep jobs only 14 days, all i need to do is to do queue.listJobs, iterate through them and decide by date if i want to do job.removeJob, correct?

Is queue.shutdown and job.removeJob all that i need to do in order to keep my program clean and running 24/7, given that there there will be new workers (of different type, type of worker contains date with millis) and new jobs all the time?

Thank you so much for your help!

**Comment by hajipy** [comment]
> Wow, that was very fast, thanks a lot!

I just got the email in my free time. I'm glad I was able to answer quickly.

> e.g. keep jobs only 14 days, all i need to do is to do queue.listJobs, iterate through them and decide by date if i want to do job.removeJob, correct?

This method is also fine, but it may be simpler to use Queue.removeJobsByCallback.

This library was created for integration into Electron, i.e., a desktop application. In my own use case, it has been stable for several weeks of continuous running, but I have not tried it beyond that.

If you are aiming for 24/7 operation, you may want to consider using a more stable library if so, as it will probably be run on a server.

**Comment by emcodem** [comment]
OK got that. Thanks and i'll let you know if i find anything that disturbs 24/7 operations :D
